version: '3'

services:
  mysql:
    image: mysql:8.0.23
    container_name: dev_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_DATABASE: demo_weapons_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
